# Generated by Django 3.2.12 on 2023-04-26 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('codigoQR', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentroComercialEspecifico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('cantidadLugares', models.IntegerField(default=0)),
                ('niveles', models.IntegerField(default=0)),
                ('qr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codigoqr', to='codigoQR.codigoqr')),
            ],
        ),
        migrations.CreateModel(
            name='Lugares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lugar', models.CharField(max_length=30)),
                ('status', models.BooleanField(default=True)),
                ('nivel', models.CharField(max_length=30)),
                ('id_cc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lugares_cc', to='estacionamiento.centrocomercialespecifico')),
            ],
        ),
        migrations.CreateModel(
            name='LugaresOcupados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('hora_entrada', models.DateTimeField(auto_now_add=True)),
                ('hora_salida', models.DateTimeField(blank=True, null=True)),
                ('available', models.BooleanField(default=True)),
                ('id_lugar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estacionamiento.lugares')),
                ('qr_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cQR', to='codigoQR.codigoqr')),
            ],
        ),
    ]
