# Generated by Django 3.2.12 on 2023-05-08 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CentroComercialEspecifico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('cantidadLugares', models.IntegerField(default=0)),
                ('niveles', models.IntegerField(default=0)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='qr_Code')),
                ('contenido', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lugar', models.CharField(max_length=30)),
                ('status', models.BooleanField(default=True)),
                ('nivel', models.IntegerField(default=0)),
                ('codigo_qr', models.ImageField(blank=True, null=True, upload_to='qr_code')),
                ('id_cc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lugares_cc', to='estacionamiento.centrocomercialespecifico')),
            ],
        ),
        migrations.CreateModel(
            name='LugarOcupado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('hora_entrada', models.TimeField(blank=True, null=True)),
                ('lugar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estacionamiento.lugar')),
            ],
        ),
    ]
