# Generated by Django 3.2.12 on 2023-04-26 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estacionamiento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lugaresocupados',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lugaresocupados',
            name='hora_entrada',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
