# Generated by Django 3.2.12 on 2023-04-13 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estacionamiento', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='centrocomerciales',
            old_name='nombreCC',
            new_name='nameCC',
        ),
    ]
