# Generated by Django 3.2.12 on 2023-05-19 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estacionamiento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centrocomercialespecifico',
            name='nombre',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
