# Generated by Django 3.2.12 on 2023-04-26 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estacionamiento', '0002_auto_20230426_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lugaresocupados',
            name='hora_salida',
        ),
    ]
