# Generated by Django 3.2.12 on 2023-04-14 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('estacionamiento', '0002_rename_nombrecc_centrocomerciales_namecc'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentroComercialEspecifico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('lugares', models.IntegerField(default=0)),
                ('niveles', models.IntegerField(default=0)),
                ('direccion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CentrosComerciales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estacionamiento.centrocomercialespecifico')),
            ],
        ),
        migrations.CreateModel(
            name='Lugares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lugar', models.CharField(max_length=30)),
                ('status', models.BooleanField(default=True)),
                ('nivel', models.CharField(max_length=30)),
                ('id_cc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lugares_cc', to='estacionamiento.centrocomercialespecifico')),
            ],
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_usuario', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
                ('apellido', models.CharField(max_length=300)),
                ('mail', models.EmailField(max_length=200)),
                ('id_cc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estacionamiento.centrocomercialespecifico')),
                ('tipo_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estacionamiento.tipousuario')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='CentroComerciales',
        ),
    ]
