# Generated by Django 3.2.12 on 2023-04-26 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estacionamiento', '0003_remove_lugaresocupados_hora_salida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lugaresocupados',
            name='hora_entrada',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
