# Generated by Django 3.2.12 on 2023-05-30 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estacionamiento', '0005_alter_lugar_lugar'),
    ]

    operations = [
        migrations.AddField(
            model_name='lugar',
            name='codigo_qr_expiracion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
