# Generated by Django 3.2.12 on 2023-06-05 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estacionamiento', '0007_alter_lugar_lugar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lugar',
            name='codigo_qr_expiracion',
        ),
    ]
