# Generated by Django 3.2.12 on 2023-06-09 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estacionamiento', '0008_remove_lugar_codigo_qr_expiracion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='centrocomercialespecifico',
            name='contenido',
        ),
    ]
