# Generated by Django 3.2.12 on 2023-04-17 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estacionamiento', '0003_auto_20230414_2000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estacionamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_entrada', models.DateTimeField(auto_now_add=True)),
                ('hora_salida', models.DateTimeField(blank=True, null=True)),
                ('qr', models.TextField(blank=True, null=True)),
                ('lugar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estacionamiento.lugares')),
            ],
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='id_cc',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='tipo_usuario',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='CentrosComerciales',
        ),
        migrations.DeleteModel(
            name='TipoUsuario',
        ),
        migrations.DeleteModel(
            name='Usuarios',
        ),
    ]
