# Generated by Django 3.2.12 on 2023-04-17 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estacionamiento', '0004_auto_20230417_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estacionamiento',
            name='qr',
        ),
        migrations.AddField(
            model_name='estacionamiento',
            name='assigned_to',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='estacionamiento',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='estacionamiento',
            name='qr_code',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
