# Generated by Django 3.2.12 on 2023-04-21 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codigoQR', '0005_alter_codigoqr_imagen'),
        ('estacionamiento', '0005_auto_20230417_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estacionamiento',
            name='qr_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cQR', to='codigoQR.codigoqr'),
        ),
    ]
