# Generated by Django 3.2.12 on 2023-04-21 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codigoQR', '0005_alter_codigoqr_imagen'),
        ('estacionamiento', '0007_remove_estacionamiento_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='centrocomercialespecifico',
            name='qr',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='codigoqr', to='codigoQR.codigoqr'),
            preserve_default=False,
        ),
    ]
