# Generated by Django 3.2.12 on 2023-04-21 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estacionamiento', '0008_centrocomercialespecifico_qr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='centrocomercialespecifico',
            name='direccion',
        ),
    ]
