# Generated by Django 3.2.12 on 2023-04-21 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codigoQR', '0006_codigoqrcentrocomercial'),
        ('estacionamiento', '0009_remove_centrocomercialespecifico_direccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='LugaresOcupados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_entrada', models.DateTimeField(auto_now_add=True)),
                ('hora_salida', models.DateTimeField(blank=True, null=True)),
                ('available', models.BooleanField(default=True)),
                ('lugar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estacionamiento.lugares')),
                ('qr_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cQR', to='codigoQR.codigoqr')),
            ],
        ),
        migrations.RenameField(
            model_name='centrocomercialespecifico',
            old_name='lugares',
            new_name='cantidadLugares',
        ),
        migrations.DeleteModel(
            name='Estacionamiento',
        ),
    ]
