# Generated by Django 3.2.12 on 2023-04-21 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estacionamiento', '0010_auto_20230421_1949'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lugaresocupados',
            old_name='lugar',
            new_name='id_lugar',
        ),
    ]
