# Generated by Django 3.2.12 on 2023-04-24 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estacionamiento', '0011_rename_lugar_lugaresocupados_id_lugar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lugaresocupados',
            name='available',
        ),
    ]
