# Generated by Django 3.2.12 on 2023-04-24 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estacionamiento', '0012_remove_lugaresocupados_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='lugaresocupados',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
