# Generated by Django 3.2.12 on 2023-04-20 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codigoQR', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codigoqr',
            name='imagen',
        ),
        migrations.AddField(
            model_name='codigoqr',
            name='titulo',
            field=models.CharField(default=True, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='codigoqr',
            name='contenido',
            field=models.TextField(),
        ),
    ]
