# Generated by Django 3.2.12 on 2023-04-21 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codigoQR', '0003_auto_20230421_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='codigoqr',
            name='name',
            field=models.CharField(default=True, max_length=200),
            preserve_default=False,
        ),
    ]
