# Generated by Django 3.2.12 on 2023-04-21 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codigoQR', '0004_codigoqr_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigoqr',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='qr_Code'),
        ),
    ]
