# Generated by Django 3.2.12 on 2023-04-26 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoQR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contenido', models.CharField(max_length=200)),
                ('imagen', models.ImageField(blank=True, upload_to='qr_Code')),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CodigoQRCentroComercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contenido', models.CharField(max_length=200)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='qr_Code')),
                ('available', models.BooleanField(default=True)),
            ],
        ),
    ]
