# Generated by Django 3.2.12 on 2023-06-02 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datosusuarios',
            name='tipoUsuario',
        ),
    ]
