# Generated by Django 3.2.12 on 2023-06-02 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_datosusuarios_tipousuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosusuarios',
            name='tipoUsuario',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.tipousuarios'),
        ),
        migrations.AlterField(
            model_name='datosusuarios',
            name='usuario',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tipousuarios',
            name='tipo_usuario',
            field=models.CharField(choices=[('Administrador', 'Administrador'), ('Centro Comercial', 'Centro Comercial'), ('Scanner QR', 'Scanner QR')], max_length=101),
        ),
    ]
