# Generated by Django 3.2.12 on 2023-06-02 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_datosusuarios_centrocomercial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosusuarios',
            name='password',
            field=models.CharField(default=True, max_length=128),
        ),
    ]
