# Generated by Django 3.2.12 on 2023-06-02 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_datosusuarios_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datosusuarios',
            name='centroComercial',
        ),
    ]
