# Generated by Django 3.2.12 on 2023-06-02 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_datosusuarios_centrocomercial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datosusuarios',
            name='centroComercial',
        ),
    ]
